### ISSUE TITLE
How to a custom cloth for test?

### ISSUE THREAD

**Issue by realaiCV** [Dolorousrtur/HOOD#1]
Hi, 
the demo video is amazing!
Now I want to test some custom cloth not in garment_meshes.
could you provide some tips how to build a new garment mesh like in garments_dict.pkl ?
Thanks!

**Comment by Dolorousrtur** [comment]
Hi, glad you like it!

If you already have a .obj file with the garment mesh that is aligned with the canonical SMPL body, you can follow the section `Add your own garment from an .obj file` in the `Inference.ipynb`. This will add your garment to `garments_dict.pkl`.

If you want to create a new garment completely from scratch, you can follow one of the numerous tutorials on how to create garments in Blender, export it as an .obj file and then add the garment to `garments_dict.pkl`

**Comment by realaiCV** [comment]
@Dolorousrtur 
yeah, I have tested a custom mesh flollowed by Inference.ipynb. 
But I got the error
`File "/home/name/garment/HOOD/utils/mesh_creation.py", line 145, in add_coarse_edges
    center_nodes = nx.center(G)
  File "/home/avatar/anaconda3/envs/hood/lib/python3.9/site-packages/networkx/algorithms/distance_measures.py", line 543, in center
    e = eccentricity(G, weight=weight)
  File "/home/avatar/anaconda3/envs/hood/lib/python3.9/site-packages/networkx/algorithms/distance_measures.py", line 317, in eccentricity
    raise nx.NetworkXError(msg)
networkx.exception.NetworkXError: Found infinite path length because the graph is not connected`

the custom obj blew
[cloth.zip](https://github.com/Dolorousrtur/HOOD/files/11925844/cloth.zip)

but I cannot konw how to set center and coarse_edges in garments_dict.pkl
could you explain in more detail?

thanks

**Comment by Dolorousrtur** [comment]
Oh, I see, that is because the garment consists of disconnected pieces. It should be a single mesh with a path between each pair of nodes. You can check this by choosing any vertex in blender and pressing ctrl+l, it will select all connected nodes. In your example, the straps are disconnected from the main body (see picture).

![image](https://github.com/Dolorousrtur/HOOD/assets/9041552/b2cc89fb-4f48-4e14-8f38-af2321d8e968)

The center and the coarse edges are added automatically inside `add_garment_to_garments_dict` function, you don't need to worry about that. It's just that networkx freaks out due to the disconnected subgraphs in your garment.

**Comment by realaiCV** [comment]
@Dolorousrtur 
Thanks, I have modified rhe mesh, and the result is amazing.

**Comment by Dolorousrtur** [comment]
Great!

**Comment by Cao-Cong0** [comment]
> @Dolorousrtur Thanks, I have modified rhe mesh, and the result is amazing.

@realaiCV Hello! I faced the same problem. I am wondering how to modify the mesh to make the separate meshes as a single one?
